version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dockerdb
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: "docker"
    ports:
      - 5432:5432

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
